### ISSUE TITLE
Breaks when other files than JS files are found

### ISSUE THREAD

**Issue by mgrsskls** [getify/moduloze#4]
Hi Kyle,

thank you for this package, it would be _really_ helpful for me right now! Unfortunately it seems to break when there are other files than JS files in `from` (in my case HTML files). When running `mz` via CLI I get: `SyntaxError: Unexpected character '' (1:0)`. After removing the HTML files it works.

If you are open for it, I could also try to create a PR in the next days.

Thanks,
Michael

**Comment by getify** [comment]
There's a [`skip` config](https://github.com/getify/moduloze#cli-only-configurations), and even a `copyOnSkip` config (to just copy them over). Does that work for you?

**Comment by mgrsskls** [comment]
Oh yes, I had interpreted the `skip` option more like "skip these JS files", but obviously it could also be used for other files. Thanks a lot :)

One really minor thing I noticed: it would be very convenient if the `to` folder gets automatically created if it doesn't exist.

**Comment by getify** [comment]
> it would be very convenient if the to folder gets automatically created if it doesn't exist.

I considered that at one point, but it seemed a little more dangerous to have you specify a directory name (not a default one) that didn't exist, as it seemed like it might be a mistake (where you typo'd the target).

The output directory it *does* automatically create is the default `./.mz-build` directory, as shown here: https://github.com/getify/moduloze/blob/2f3a1f99b800366d436d8c4efd191fd435afb4f8/src/cli.js#L239-L249

I could consider an option to override this and always create the target dir. But I think the way it currently is seems a safer default. Would a config option (like `forceToPath` or something) suffice?

**Comment by mgrsskls** [comment]
In my opinion it's okay that a new directory gets created (in my use case a new directory is what I want) - if any the user could just rename it (correct me if I'm missing some possible negative side effects). But sure, an option like that would also be fine!
